-- Script para verificar as colunas das tabelas relacionadas à régua de cobrança
-- Execute este script no banco ClienteMais CRM para verificar se as colunas existem

-- Verificar colunas da tabela TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO'
ORDER BY ORDINAL_POSITION;

-- Verificar colunas da tabela TB_CMCRM_CASO_COBRANCA_REGUA_TIPO_ACAO
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TB_CMCRM_CASO_COBRANCA_REGUA_TIPO_ACAO'
ORDER BY ORDINAL_POSITION;

-- Verificar especificamente as colunas que devem existir
SELECT 
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CMCRM_CASO_COBRANCA_REGUA_TIPO_ACAO' AND COLUMN_NAME = 'FL_ACAO_AGENDADA')
        THEN 'EXISTS' ELSE 'NOT EXISTS' 
    END AS FL_ACAO_AGENDADA_Status_Na_TabelaTipoAcao,
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO' AND COLUMN_NAME = 'ID_TEMPLATE_MRS')
        THEN 'EXISTS' ELSE 'NOT EXISTS' 
    END AS ID_TEMPLATE_MRS_Status,
    CASE 
        WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO' AND COLUMN_NAME = 'ID_TIPO_POSTAGEM')
        THEN 'EXISTS' ELSE 'NOT EXISTS' 
    END AS ID_TIPO_POSTAGEM_Status;

-- Se as colunas não existirem, você pode criá-las com:
/*
-- FL_ACAO_AGENDADA deve estar na tabela TB_CMCRM_CASO_COBRANCA_REGUA_TIPO_ACAO
ALTER TABLE TB_CMCRM_CASO_COBRANCA_REGUA_TIPO_ACAO
ADD FL_ACAO_AGENDADA BIT NOT NULL DEFAULT 0;

-- ID_TEMPLATE_MRS e ID_TIPO_POSTAGEM devem estar na tabela TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO
ALTER TABLE TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO
ADD ID_TEMPLATE_MRS VARCHAR(5) NULL;

ALTER TABLE TB_CMCRM_CASO_COBRANCA_REGUA_ETAPA_ACAO
ADD ID_TIPO_POSTAGEM VARCHAR(5) NULL;
*/
